nacos:
  discovery:
    server-addr: 127.0.0.1:8848
dubbo:
  application:
    name: dubbo-provider-demo
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: -1
#扫描基础包
  scan:
    base-packages: ywh.whworld.service.impl


demo:
  service:
    version: 1.0.0
    name: demoService

server:
  port: 9005

spring:
  application:
    name: ywh-provider
